import type { Metadata } from "next"
import { ToastContainer } from "react-toastify"
import "./globals.css"
import Sidebar from "./components/Sidebar"

export const metadata: Metadata = {
  title: "Fluxcore - Controle de processos",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#28303E]">
        <div className="flex">
          <ToastContainer theme="dark" />
          <Sidebar />
          <main className="flex-1 p-6 bg-[#F6EEFF]">{children}</main>
        </div>
      </body>
    </html>
  )
}
